### PR TITLE
Fix Cms/Classes not found when CMS module isn't loaded in config/cms.php

### LINKED ISSUE #43: Incompatibility when module CMS is disabled. (Cms\Classes not found)
Hi, I am mainly using WinterCMS as a backend+api with JS framework as front-end (React, Vue...).
Most of the time I **disable CMS module** in config/cms.php (loadModules).

Blog plugin was working well until last winter update 1.2.x
I **re-enabled CMS Module** to allow use of CMS\Classes.

```
Error: Class "Cms\Classes\Theme" not found in /var/www/xxxxx/plugins/winter/blog/models/Post.php:394
```

https://github.com/wintercms/wn-blog-plugin/blob/main/models/Post.php#L394

### PR DESCRIPTION
**Pull request by AdrienAdB**
Fix #43 
Cms/Classes not found when CMS module isn't loaded in config/cms.php

### CODE REVIEW

File: models/Category.php [hunk 1]
```diff
@@ -104,6 +104,14 @@ public static function getMenuTypeInfo(string $type): array
     {
         $result = [];
 
+        if (!class_exists(Theme::class)) {
+            return $result;
+        }
+
+        if (!class_exists(CmsPage::class)) {
+            return $result;
+        }
```
Comment (bennothommo) [inline models/Category.php:113]: @AdrienAdB you can probably drop the second class existence checks - if the `Theme` class is there, it's pretty much a given that the `CmsPage` class will also be there.
```suggestion
```

File: models/Category.php [hunk 2]
```diff
@@ -104,6 +104,11 @@ public static function getMenuTypeInfo(string $type): array
     {
         $result = [];
 
+        if (!class_exists(Theme::class)) {
+            return $result;
+        }
+
```
Comment (LukeTowers) [inline models/Category.php:110]:
```suggestion
```

File: models/Post.php [hunk 3]
```diff
@@ -391,6 +391,14 @@ public function getCmsPageOptions(): array
     {
         $result = [];
 
+        if (!class_exists(Theme::class)) {
+            return $result;
+        }
+
+        if (!class_exists(CmsPage::class)) {
+            return $result;
+        }
```
Comment (LukeTowers) [inline models/Post.php:400]:
```suggestion
```

File: models/Post.php [hunk 4]
```diff
@@ -562,6 +566,15 @@ public static function getMenuTypeInfo(string $type): array
...
 
         if ($result) {
+
+            if (!class_exists(Theme::class)) {
+                return $result;
+            }
+
+            if (!class_exists(CmsPage::class)) {
+                return $result;
+            }
```
Comment (LukeTowers) [inline models/Post.php:576]:
```suggestion
            if (!class_exists(Theme::class)) {
                return $result;
            }
```
